version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: mongo
    image: mongo
    restart: always

  # Node api service
  api:
    build: .
    ports:
      # local->container
      - 8888:8888
    environment:
      PORT: 8888
      MONGOURL: mongodb://mongo_db:27017
    depends_on: 
      - mongo_db

volumes:
  mongo_data: {}
